name: Afra
version: '${project.version}'
main: it.itzsamirr.afra.Afra
api-version: 1.8
permissions:
  afra.*:
    default: op
    children:
      - afra.bypass.*
  afra.bypass.*:
    description: permission to bypass all checks
authors: [ ItzSamirr ]
