name: Afra
version: '${project.version}'
main: it.itzsamirr.afra.Afra
api-version: 1.8
permissions:
  afra.*:
    default: op
    children:
      - afra.bypass.*
      - afra.alerts
  afra.alerts:
    description: permission to get the alerts of the anticheat
  afra.bypass.*:
    description: permission to bypass all checks
authors: [ ItzSamirr ]
